### ISSUE TITLE
Check metadata

### ISSUE THREAD

**Issue by damianooldoni** [riparias/pov-fishes-occurrences#24]
We should first solve https://github.com/riparias/pov-ias-plants-occurrences/issues/37 and publish the pov-ias-plants dataset. Once decided for that dataset, we can easily apply the changes to this dataset as well.
Metadata Google document: https://docs.google.com/document/d/1O-Z-8CILE9asZlI0HA_tJWVO31S1SifZbmbeXtD7h8g/edit#

**Comment by LienReyserhove** [comment]
I see that the title was still the old one, i.e. `Monitoring of fishes and crustacea by the Provincial Center of Environmental Research (PCM) in East Flanders, Belgium`. I changed this to `Monitoring of fishes and crustacea by the province East Flanders, Belgium`

**Comment by damianooldoni** [comment]
Thank @LienReyserhove very much, you are my hero!

**Comment by LienReyserhove** [comment]
Metadata uploaded, issue can be closed I guess :-)
