### ISSUE TITLE
License correct?

### ISSUE THREAD

**Issue by LienReyserhove** [riparias/pov-fishes-occurrences#29]
While inspecting the dataset, I found this license: `https://creativecommons.org/licenses/by-nc/4.0/legalcode`.
This conflicts with the license in the metadata, which is CC BY. I would also suggest the last one, not the CC BY-NC.
Why did we choose for the CC BY-NC? 

See also https://github.com/riparias/pov-ias-plants-occurrences/issues/48

**Comment by damianooldoni** [comment]
I asked to @filipmahieu via mail.

**Comment by damianooldoni** [comment]
License CC-BY has been chosen and included in the DwC mapping.
