### ISSUE TITLE
Use of synonyms vs accepted species names

### ISSUE THREAD

**Issue by sannegovaert** [riparias/pov-fishes-occurrences#96]
In the raw data, some synonym names (according to GBIF) are used.

accepted name | synonym | in dataset 23/09 | comment
-- | -- | -- | --
Leuciscus aspius | [Aspius aspius](https://www.gbif.org/species/2360181) | synonym
Carassius gibelio | [Carassius auratus gibelio](https://www.gbif.org/species/6166945) | synonym
Gymnocephalus cernua | [Gymnocephalus cernuus](https://www.gbif.org/species/2382126) | synonym
Squalius cephalus | [Leuciscus cephalus](https://www.gbif.org/species/5207464) | synonym
Cyprinella rutila | [Leuciscus rutilus](https://www.gbif.org/search?q=Leuciscus%20rutilus) | synonym | [not mapped on GBIF](https://www.gbif.org/occurrence/search?q=Leuciscus%20rutilus&dataset_key=ba1bf66f-863b-46c7-bdce-ec5853c16c55)
Chelon ramada | [Liza ramada](https://www.gbif.org/species/2400718) | synonym
Cyprinella rutila | [Rutilus erythrophthalmus](https://www.gbif.org/species/5205634) | synonym
Sander lucioperca | [Stizostedion lucioperca](https://www.gbif.org/species/2382158) | synonym

GBIF links the synonyms, so if you search for _Leuciscus aspius_ you will also see the observations of _Aspius aspius_. But this link is only in 1 direction. 
However, [Leuciscus rutilus](https://www.gbif.org/search?q=Leuciscus%20rutilus)  is not mapped to the accepted species name, because it is ambiguous.
@filipmahieu how do you want me to deal with this in the data? Do we keep the synonym or do we map it to the accepted names?

Also, probably some typo's:
accepted name | in dataset
-- | --
Abramis brama | Abramis Brama
Umbra pygmaea | Umbra Pygmaea
Barbatula barbatula | Barbatula barbatulus
Ctenopharyngodon idella | Ctenopharyngodon idellia

**Comment by filipmahieu** [comment]
Hi, we had a look, at last.. thanks for your patience. 
- typo's are corrected
- Leuciscus rutilus (Blankvoorn): Rutilus rutilus should be used, not Cyprinella rutila . Changed in our database
- Rietvoorn: is Scardinius erythrophtalmus (not Cyprinella rutila or Rutilus erythrophtalmus). Changed in our database
- other synonyms are changed to the accepted name. Changed in our database

**Comment by sannegovaert** [comment]
> Hi, we had a look, at last.. thanks for your patience.
> 
> * typo's are corrected
> * Leuciscus rutilus (Blankvoorn): Rutilus rutilus should be used, not Cyprinella rutila . Changed in our database
> * Rietvoorn: is Scardinius erythrophtalmus (not Cyprinella rutila or Rutilus erythrophtalmus). Changed in our database
> * other synonyms are changed to the accepted name. Changed in our database

Great, thank you Filip!
